In [1]:
# Google Colab 운영체제 확인
import platform
print(platform.platform())

Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic


In [2]:
# 텐서플로우 불러오기, 버전 확인
import tensorflow as tf
print(tf.__version__)

2.4.1


## 랜덤한 수 생성

In [3]:
# 랜덤한 수 얻기 (균일 분포)
rand = tf.random.uniform([1],0,1)
print(rand)

tf.Tensor([0.39049363], shape=(1,), dtype=float32)


In [4]:
# 랜덤한 수 여러 개 얻기 (균일 분포)
rand = tf.random.uniform([4],0,1)
print(rand)

tf.Tensor([0.8860891  0.9118389  0.25379324 0.6998408 ], shape=(4,), dtype=float32)


In [5]:
# 랜덤한 수 여러 개 얻기 (정규 분포)
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([ 1.6146839 -0.6433361 -2.1183646  1.7698756], shape=(4,), dtype=float32)


## 뉴런 만들기

In [6]:
# sigmoid 함수 : 0~1 사이값으로 제한해서 리턴

import math

def sigmoid(x):
    # 상수 e의 제곱을 계산하기 위해 math.exp() 사용
    # x에 시그모이드 함수를 취한 값
    return 1 / (1 + math.exp(-x))

In [8]:
# 문제 : 뉴런의 입력과 출력 정의 - 입력이 1일때 기대 출력이 0이 되는 뉴런 만들어 보기 가정


# 기대 출력이 0이라 할 경우 차를 error라 함
# 뉴런의 학습의 주 목적 = 이 에러가 0에 가까워지게 해서 출력으로 기댓값에 가까운 값을 얻는 것

x = 1   # 입력
y = 0   # 기대값 문제 : 뉴런의 입력과 출력 정의 - 입력이 1일때 기대 출력이 0이 되는 뉴런 만들어 보기 가정


# 딥러닝 관점 : 가중치는 수작업으로 도출하기가 어려움
# 가중치로 정규 분포의 랜덤한 값
w = tf.random.normal([1],0,1)  # 정규 분포의 난수 구하는 함수 

output = sigmoid(x * w)
print(output)

0.31186307262470747


In [9]:
# 경사 하강법을 이용한 뉴런의 학습
# w에 입력과 학습률과 에러를 곱한 값을 더해줌
# 학습률은 w를 업데이트하는 정도
# a = 0.1로 설정

'''
0~999까지 1000번 반복
error 는 기대출력인 y에서 실제 출력인 output 빼기
여러번 반복해서 x가 1일때 y값이 0에 가까워짐을 확인
'''
for i in range(1000):
    output = sigmoid(x * w)
    error = y - output  # 기대값 - 연산된 결과값 = error값 도출 

    # 각중치 값을 에러가 최소가 될수 있도록 업데이트 하기 위해서 지속적인 변경이 가능하겠금 구현한 로직
    # 지속적인 변경 작업이 수행되는 action - 학습
    # 딥러닝 관점에선 - learning rate라 표현
    # 딥러닝은 결국엔 수치 연산 따라서 조금씩 연산이 지속되겠금 일정 수치값 반경(개발자가 지정)
    # 0.1 값으로 초기치(하이퍼마라미터)
    # 식 도출은 다양하게 나올수는 있으나 딥러닝 내부적으로 적용한 연산식으로 간주
    # 최적의 해를 찾아가기 위한 학습 연산식
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
        print('순번 : ', i, ' 에러 : ', error, ' 출력 : ', output)

'''
0에 가장 근접한 가중치값을 학습을 통해서 999번째 도출
'''

순번 :  99  에러 :  -0.08619552279266572  출력 :  0.08619552279266572
순번 :  199  에러 :  -0.0476265722405048  출력 :  0.0476265722405048
순번 :  299  에러 :  -0.032655618405828424  출력 :  0.032655618405828424
순번 :  399  에러 :  -0.02478169860673977  출력 :  0.02478169860673977
순번 :  499  에러 :  -0.019943737330033157  출력 :  0.019943737330033157
순번 :  599  에러 :  -0.016675654584596876  출력 :  0.016675654584596876
순번 :  699  에러 :  -0.014322368288382705  출력 :  0.014322368288382705
순번 :  799  에러 :  -0.012548086978579983  출력 :  0.012548086978579983
순번 :  899  에러 :  -0.011163098918160112  출력 :  0.011163098918160112
순번 :  999  에러 :  -0.010052254774803777  출력 :  0.010052254774803777


In [10]:
# x=0 일 때 y=1 을 얻는 뉴런의 학습시키기
# 편향의 필요성 인지하기

'''
문제발생 : error와 출력 모두 0.5로 변하지 않음
입력값 0  따라서 w에 더해지는 데이터는 없음, 즉 1000번 실행하는 동안 w 값 변동 없음
'''

x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error
    
    if i % 100 == 99:
       print('순번 : ', i, ' 에러 : ', error, ' 출력 : ', output)

순번 :  99  에러 :  0.5  출력 :  0.5
순번 :  199  에러 :  0.5  출력 :  0.5
순번 :  299  에러 :  0.5  출력 :  0.5
순번 :  399  에러 :  0.5  출력 :  0.5
순번 :  499  에러 :  0.5  출력 :  0.5
순번 :  599  에러 :  0.5  출력 :  0.5
순번 :  699  에러 :  0.5  출력 :  0.5
순번 :  799  에러 :  0.5  출력 :  0.5
순번 :  899  에러 :  0.5  출력 :  0.5
순번 :  999  에러 :  0.5  출력 :  0.5


In [11]:
# 해결책 : 편향(bias)이라는 것 적용
# x=0 일 때 y=1 을 얻는 뉴런의 학습에 편향을 더함

'''
입력으로는 늘 한쪽으로 치우진 고정된 값 가령 1을 받아서 입력으로 0을 받았을 때 

* 뉴런이 아무것도 배우지 못하는 상황 방지 : 수치값 추가

편향은 w 처럼 난수로 초기화되며 뉴런에 더해져서 출력 계산

결론 : error는 0에 가까워짐, output은 1에 가까워짐
'''

x = 0  # 입력
y = 1  # 기대값 

w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)

for i in range(1000):
    output = sigmoid(x * w + 1 * b)
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print('순번 : ', i, ' 에러 : ', error, ' 출력 : ', output)

순번 :  99  에러 :  0.12341400357990795  출력 :  0.876585996420092
순번 :  199  에러 :  0.05777139080098492  출력 :  0.9422286091990151
순번 :  299  에러 :  0.03721579245215467  출력 :  0.9627842075478453
순번 :  399  에러 :  0.027346749652072844  출력 :  0.9726532503479272
순번 :  499  에러 :  0.021581234142918904  출력 :  0.9784187658570811
순번 :  599  에러 :  0.01780935996687749  출력 :  0.9821906400331225
순번 :  699  에러 :  0.015152835899267636  출력 :  0.9848471641007324
순번 :  799  에러 :  0.013182199345650458  출력 :  0.9868178006543495
순번 :  899  에러 :  0.011662867162453572  출력 :  0.9883371328375464
순번 :  999  에러 :  0.010456186200330952  출력 :  0.989543813799669
